db.biobank.insert({
    "id": "",
    "identifier": "BB-0033-99990",
    "name": "biobank n\u00b0 0",
    "long_name": "Biobanque 0 - CRB0 - Paris",
    "collection_name": "HCL- Immunobiotec",
    "collection_id": "HCL- Immunobiotec",
    "biobank_class": "biobankClinical",
    "date_entry": "",
    "folder_reception": "",
    "folder_done": "",
    "passphrase": "",
    "contact_id": "",
    "diagnosis_available": "M00-M99",
    "pathologies": null,
    "pathologies_en": null,
    "longitude": "4,8997208",
    "latitude": "45,7474263",
    "location": {
        "type": "Point",
        "coordinates": [
            4.8997208,
            45.7474263
        ]
    },
    "keywords_MeSH": "",
    "keywords_MeSH_fr": null,
    "acronym": "",
    "presentation": null,
    "presentation_en": null,
    "vitrine": null,
    "sampling_practice": "",
    "materialStoredPlasma": "",
    "materialStoredRNA": null,
    "materialStoredSaliva": null,
    "materialStoredSerum": "",
    "materialStoredTissueFFPE": "",
    "materialStoredTissueFrozen": "",
    "materialStoredUrine": null,
    "materialStoredBlood": null,
    "materialStoredDNA": "",
    "materialStoredFaeces": null,
    "materialStoredImmortalizedCellLines": null,
    "materialTumoralTissue": null,
    "materialHealthyTissue": null,
    "materialLCR": null,
    "materialOther": null,
    "sampling_disease_group": "",
    "sampling_disease_group_code": "",
    "nb_total_samples": null,
    "collectionDataAccessFee": "TRUE",
    "collectionDataAccessJointProjects": "TRUE",
    "collectionSampleAccessFee": "TRUE",
    "collectionSampleAccessJointProjects": "TRUE",
    "PartnerCharterSigned": "",
    "nbs_dna_samples_affected": "",
    "nbs_dna_samples_relatives": "",
    "nbs_cdna_samples_affected": "",
    "nbs_cdna_samples_relatives": "",
    "nbs_wholeblood_samples_affected": "",
    "nbs_wholeblood_samples_relatives": "",
    "nbs_bloodcellisolates_samples_affected": "",
    "nbs_bloodcellisolates_samples_relatives": "",
    "nbs_serum_samples_affected": "",
    "nbs_serum_samples_relatives": "",
    "nbs_plasma_samples_affected": "",
    "nbs_plasma_samples_relatives": "",
    "nbs_fluids_samples_affected": "",
    "nbs_fluids_samples_relatives": "",
    "nbs_tissuescryopreserved_samples_affected": "",
    "nbs_tissuescryopreserved_samples_relatives": "",
    "nbs_tissuesparaffinembedded_samples_affected": "",
    "nbs_tissuesparaffinembedded_samples_relatives": "",
    "nbs_celllines_samples_affected": "",
    "nbs_celllines_samples_relatives": "",
    "nbs_other_samples_affected": "",
    "nbs_other_samples_relatives": "",
    "nbs_other_specification": "",
    "cims": [],
    "contact_search": "",
    "cert_ISO9001": "NON",
    "cert_NFS96900": "NON",
    "cert_autres": "\/"
});
db.biobank.insert({
    "id": "3",
    "identifier": "BB-0033-99991",
    "name": "biobank n\u00b0 1",
    "long_name": "Biobanque 1 - CRB1 - Paris",
    "collection_name": "ISPED Foie Bordeaux",
    "collection_id": "ISPED Foie Bordeaux",
    "biobank_class": "biobankClinical",
    "date_entry": "",
    "folder_reception": "\/inserm_sftp\/bordeaux\/reception\/",
    "folder_done": "\/inserm_sftp\/bordeaux\/inclusion\/",
    "passphrase": "",
    "contact_id": "552fe5e90175447b308b45da",
    "diagnosis_available": "C00",
    "pathologies": null,
    "pathologies_en": null,
    "longitude": null,
    "latitude": null,
    "location": null,
    "keywords_MeSH": null,
    "keywords_MeSH_fr": null,
    "acronym": null,
    "presentation": null,
    "presentation_en": null,
    "vitrine": null,
    "sampling_practice": null,
    "materialStoredPlasma": null,
    "materialStoredRNA": null,
    "materialStoredSaliva": null,
    "materialStoredSerum": null,
    "materialStoredTissueFFPE": null,
    "materialStoredTissueFrozen": null,
    "materialStoredUrine": null,
    "materialStoredBlood": null,
    "materialStoredDNA": null,
    "materialStoredFaeces": null,
    "materialStoredImmortalizedCellLines": null,
    "materialTumoralTissue": null,
    "materialHealthyTissue": null,
    "materialLCR": null,
    "materialOther": null,
    "sampling_disease_group": null,
    "sampling_disease_group_code": null,
    "nb_total_samples": null,
    "collectionDataAccessFee": "TRUE",
    "collectionDataAccessJointProjects": "TRUE",
    "collectionSampleAccessFee": "TRUE",
    "collectionSampleAccessJointProjects": "TRUE",
    "PartnerCharterSigned": "TRUE",
    "nbs_dna_samples_affected": null,
    "nbs_dna_samples_relatives": null,
    "nbs_cdna_samples_affected": null,
    "nbs_cdna_samples_relatives": null,
    "nbs_wholeblood_samples_affected": null,
    "nbs_wholeblood_samples_relatives": null,
    "nbs_bloodcellisolates_samples_affected": null,
    "nbs_bloodcellisolates_samples_relatives": null,
    "nbs_serum_samples_affected": null,
    "nbs_serum_samples_relatives": null,
    "nbs_plasma_samples_affected": null,
    "nbs_plasma_samples_relatives": null,
    "nbs_fluids_samples_affected": null,
    "nbs_fluids_samples_relatives": null,
    "nbs_tissuescryopreserved_samples_affected": null,
    "nbs_tissuescryopreserved_samples_relatives": null,
    "nbs_tissuesparaffinembedded_samples_affected": null,
    "nbs_tissuesparaffinembedded_samples_relatives": null,
    "nbs_celllines_samples_affected": null,
    "nbs_celllines_samples_relatives": null,
    "nbs_other_samples_affected": null,
    "nbs_other_samples_relatives": null,
    "nbs_other_specification": null,
    "cims": [],
    "contact_search": null,
    "cert_ISO9001": null,
    "cert_NFS96900": null,
    "cert_autres": null
});
db.biobank.insert({
    "id": "2",
    "identifier": "BB-0033-99992",
    "name": "biobank n\u00b0 2",
    "long_name": "Biobanque 2 - CRB2 - Paris",
    "collection_name": "Lille Neurobank",
    "collection_id": "ET000047",
    "biobank_class": "biobankClinical",
    "date_entry": "",
    "folder_reception": "\/inserm_sftp\/lille\/reception\/",
    "folder_done": "\/inserm_sftp\/lille\/inclusion\/",
    "passphrase": "pg59nic",
    "contact_id": "52e00282975af51ac91e8429",
    "diagnosis_available": "G00-G99 \/ F00-F99 \/ K00-K93 \/ E00-E90 \/ I00-I99",
    "pathologies": null,
    "pathologies_en": null,
    "longitude": "3,0327663",
    "latitude": "50,6099648",
    "location": {
        "type": "Point",
        "coordinates": [
            3.0327663,
            50.6099648
        ]
    },
    "keywords_MeSH": "",
    "keywords_MeSH_fr": null,
    "acronym": "",
    "presentation": "Plateforme du campus hospitalo-universitaire de Lille, le CRB\/CIC1403 a \u00e9t\u00e9 cr\u00e9\u00e9 en support \u00e0 la prise en charge et \u00e0 la conservation des \u00e9chantillons biologiques des projets de recherches cliniques impliquant la constitution d\u2019une collection de ressources biologiques. Afin de garantir aux investigateurs les meilleures conditions de prise en charge de leurs \u00e9chantillons, le CRB\/CIC1403 est certifi\u00e9 selon deux r\u00e9f\u00e9rentiels : ISO9001v2008 et NF-S-96900 pour la collecte, la pr\u00e9paration, la conservation, la gestion et la distribution d\u2019\u00e9chantillons biologiques pour la recherche.",
    "presentation_en": "Created and labelled in the Clinical Investigation Center of Lille (CIC 9301 INSERM-CHU) under theauspices of INSERM, Lille University hospital and Lille2 University, the Lille University hospital Biobankgot the advantage of the experience, the funds, and the quality system advances of the CIC. It has beenfirst developed to manage biological samples generated by local clinical research projects but theBiobank has been rapidly involved in national and European research projects that lead to numerouslocal and national collaborations with teams involved in clinical or fundamental researches. Recentlyrecognised as a plate-form IBISA partner, the Lille University Hospital Biobank has an important activityaccording to the management of more than 200 000 samples with authorizations for cessions,importations and exportations. Beside quality control procedures developed for years, the Biobank isnow on pending certification particularly about samples traceability procedures. Such procedures weredeveloped in several projects including a European project, HELENA, where the Lille University HospitalBiobank managed the overall movements of biological samples across 10 European countries.From a scientific point of view, the Lille University Hospital Biobank developed activities in variousfields including cardiovascular pathology, neurosciences, metabolism\/nutrition and inflammatory boweldiseases both in adult and children. These activities lead to the publication of more than 60 originalpapers in high impact journals. Among collaborations and researches, works on familial Parkinsondiseases (PARKFANORD), dementia (Lille brain biobank), genetic of inflammatory bowel diseases(NOD2, MINOTOR) and genetic of metabolic diseases and diabetes (ABOS) must particularly beunderlined.Finally, the persons in charge of the Lille University Hospital Biobank are involved in the NationalNetwork of French Biobank that leads to the development of the French Quality Norm for Biobank.Furthermore, the persons in charge of the Biobank are also involved in European collaborative projectssuch as BBMRI.",
    "vitrine": null,
    "sampling_practice": "",
    "materialStoredPlasma": "",
    "materialStoredRNA": null,
    "materialStoredSaliva": null,
    "materialStoredSerum": "",
    "materialStoredTissueFFPE": "",
    "materialStoredTissueFrozen": "",
    "materialStoredUrine": null,
    "materialStoredBlood": null,
    "materialStoredDNA": "",
    "materialStoredFaeces": null,
    "materialStoredImmortalizedCellLines": null,
    "materialTumoralTissue": null,
    "materialHealthyTissue": null,
    "materialLCR": null,
    "materialOther": null,
    "sampling_disease_group": "",
    "sampling_disease_group_code": "",
    "nb_total_samples": null,
    "collectionDataAccessFee": "TRUE",
    "collectionDataAccessJointProjects": "TRUE",
    "collectionSampleAccessFee": "TRUE",
    "collectionSampleAccessJointProjects": "TRUE",
    "PartnerCharterSigned": "",
    "nbs_dna_samples_affected": "",
    "nbs_dna_samples_relatives": "",
    "nbs_cdna_samples_affected": "",
    "nbs_cdna_samples_relatives": "",
    "nbs_wholeblood_samples_affected": "",
    "nbs_wholeblood_samples_relatives": "",
    "nbs_bloodcellisolates_samples_affected": "",
    "nbs_bloodcellisolates_samples_relatives": "",
    "nbs_serum_samples_affected": "",
    "nbs_serum_samples_relatives": "",
    "nbs_plasma_samples_affected": "",
    "nbs_plasma_samples_relatives": "",
    "nbs_fluids_samples_affected": "",
    "nbs_fluids_samples_relatives": "",
    "nbs_tissuescryopreserved_samples_affected": "",
    "nbs_tissuescryopreserved_samples_relatives": "",
    "nbs_tissuesparaffinembedded_samples_affected": "",
    "nbs_tissuesparaffinembedded_samples_relatives": "",
    "nbs_celllines_samples_affected": "",
    "nbs_celllines_samples_relatives": "",
    "nbs_other_samples_affected": "",
    "nbs_other_samples_relatives": "",
    "nbs_other_specification": "",
    "cims": [],
    "contact_search": "",
    "cert_ISO9001": "OUI",
    "cert_NFS96900": "OUI",
    "cert_autres": ""
});
db.biobank.insert({
    "id": "4",
    "identifier": "BB-0033-99993",
    "name": "biobank n\u00b0 3",
    "long_name": "Biobanque 3 - CRB3 - Paris",
    "collection_name": "Oncologie - Canc\u00e9rologie - Cancer: Cancers broncho-pulmonaires, des voies a\u00e9ro-digestives, du rein, h\u00e9pato-cellulaire, tumeurs p\u00e9diatriques, c\u00e9r\u00e9brales, h\u00e9mopathies malignes, lymphomes",
    "collection_id": "Oncologie - Canc\u00e9rologie - Cancer: Cancers broncho-pulmonaires, des voies a\u00e9ro-digestives, du rein, h\u00e9pato-cellulaire, tumeurs p\u00e9diatriques, c\u00e9r\u00e9brales, h\u00e9mopathies malignes, lymphomes",
    "biobank_class": "biobankClinical",
    "date_entry": "",
    "folder_reception": "\/inserm_sftp\/grenoble\/reception\/",
    "folder_done": "\/inserm_sftp\/grenoble\/inclusion\/",
    "passphrase": "my6eymic",
    "contact_id": "552fe5e50175447b308b458a",
    "diagnosis_available": "C00",
    "pathologies": null,
    "pathologies_en": null,
    "longitude": "5,724524",
    "latitude": "45,188529",
    "location": {
        "type": "Point",
        "coordinates": [
            5.724524,
            45.188529
        ]
    },
    "keywords_MeSH": "",
    "keywords_MeSH_fr": null,
    "acronym": "",
    "presentation": "Le Centre de Ressources Biologique en Canc\u00e9rologie du CHU de Grenoble est d\u00e9di\u00e9 \u00e0 la th\u00e9matique cancer. Il conserve les \u00e9chantillons \u00e0 des fins sanitaire ou de recherche. Il dispose d\u2019\u00e9chantillons de type tissu tumoral et tissu sain associ\u00e9,  s\u00e9rum, plasma et cellules. En collaboration avec les pathologistes du CHU, il assure le contr\u00f4le qualit\u00e9 des pr\u00e9l\u00e8vements tissulaires.Dans le cadre de protocoles biom\u00e9dicaux, il g\u00e8re \u00e0 la demande la pr\u00e9servation \u00e0 basse temp\u00e9rature de pr\u00e9l\u00e8vements congel\u00e9s.Sur demande, il peut r\u00e9aliser l\u2019extraction ADN, ARN \u00e0 partir de tissu ou de sang et met en \u0153uvre les controles qualit\u00e9s aff\u00e9rents.",
    "presentation_en": "The Biological resource repository (CRB) is fully dedicated to cancer. This structure is funded with MERRI (French government funding). The CRB employs an engineer biologist (0.5 FTE), quality engineer (0.2 FTE), 1 clinical research technician (1ETP) 4 biologist technicians FTE. More than 70000 samples, mainly from hematological tumors, lung cancer, ENT, pediatric cancers, hepatocarcinomas and brain tumors. This structure has been certified ISO 9001 and NF - CRB. The CRB has no intrinsic scientific activity, it\u2019s main purpose is to ensure the frozen preservation of tumor tissue and biological fluid of cancer patients. The biological samples stored at the CRB are processed and transferred to our scientific partners either INSTITUT ALBERT BONNIOT Ontogen\u00e8se et Oncogen\u00e8se Mol\u00e9culaire - Inserm U823 and GRENOBLE  INSTITUT DES NEUROSCIENCES \u2013 Inserm U836 or transferred to other National or foreign institutions. All scientific partnerships are submitted for agreement to a scientific committee dedicated to review the scientific, legal and ethical aspects of research.The main scientific topics are the biology of lung cancer, lymphomas and brain tumors.National and international partnerships have been achieved in the last 4 years. It should be mentioned that a large part of these national partnerships were funded and integrated in scientific networks organized by the National Institute of Cancer (INCa).",
    "vitrine": "",
    "sampling_practice": "2",
    "materialStoredPlasma": "",
    "materialStoredRNA": null,
    "materialStoredSaliva": null,
    "materialStoredSerum": "",
    "materialStoredTissueFFPE": "",
    "materialStoredTissueFrozen": "",
    "materialStoredUrine": null,
    "materialStoredBlood": null,
    "materialStoredDNA": "",
    "materialStoredFaeces": null,
    "materialStoredImmortalizedCellLines": null,
    "materialTumoralTissue": null,
    "materialHealthyTissue": null,
    "materialLCR": null,
    "materialOther": null,
    "sampling_disease_group": "",
    "sampling_disease_group_code": "",
    "nb_total_samples": null,
    "collectionDataAccessFee": "TRUE",
    "collectionDataAccessJointProjects": "TRUE",
    "collectionSampleAccessFee": "TRUE",
    "collectionSampleAccessJointProjects": "TRUE",
    "PartnerCharterSigned": "",
    "nbs_dna_samples_affected": "",
    "nbs_dna_samples_relatives": "",
    "nbs_cdna_samples_affected": "",
    "nbs_cdna_samples_relatives": "",
    "nbs_wholeblood_samples_affected": "",
    "nbs_wholeblood_samples_relatives": "",
    "nbs_bloodcellisolates_samples_affected": "",
    "nbs_bloodcellisolates_samples_relatives": "",
    "nbs_serum_samples_affected": "",
    "nbs_serum_samples_relatives": "",
    "nbs_plasma_samples_affected": "",
    "nbs_plasma_samples_relatives": "",
    "nbs_fluids_samples_affected": "",
    "nbs_fluids_samples_relatives": "",
    "nbs_tissuescryopreserved_samples_affected": "",
    "nbs_tissuescryopreserved_samples_relatives": "",
    "nbs_tissuesparaffinembedded_samples_affected": "",
    "nbs_tissuesparaffinembedded_samples_relatives": "",
    "nbs_celllines_samples_affected": "",
    "nbs_celllines_samples_relatives": "",
    "nbs_other_samples_affected": "100000",
    "nbs_other_samples_relatives": "",
    "nbs_other_specification": "see research samples",
    "cims": [],
    "contact_search": "",
    "cert_ISO9001": "OUI",
    "cert_NFS96900": "OUI",
    "cert_autres": "\/"
});
db.biobank.insert({
    "id": "5",
    "identifier": "BB-0033-99994",
    "name": "biobank n\u00b0 4",
    "long_name": "Biobanque 4 - CRB4 - Paris",
    "collection_name": "Cancers bronchiques et m\u00e9soth\u00e9liomes pleuraux",
    "collection_id": "Cancers bronchiques et m\u00e9soth\u00e9liomes pleuraux",
    "biobank_class": "biobankClinical",
    "date_entry": "",
    "folder_reception": "\/inserm_sftp\/nancy\/reception\/",
    "folder_done": "\/inserm_sftp\/nancy\/inclusion\/",
    "passphrase": "ncy5exic",
    "contact_id": "52e00282975af51ac91e842e",
    "diagnosis_available": "C00-D48",
    "pathologies": null,
    "pathologies_en": null,
    "longitude": "6,1901887",
    "latitude": "48,6834086",
    "location": {
        "type": "Point",
        "coordinates": [
            6.1901887,
            48.6834086
        ]
    },
    "keywords_MeSH": "",
    "keywords_MeSH_fr": null,
    "acronym": "",
    "presentation": "Le CRB Cancers Bronchiques et M\u00e9soth\u00e9liomes de Nancy, situ\u00e9 au sein du service d\u2019anatomie et cytologie pathologiques a \u00e9t\u00e9 cr\u00e9\u00e9 en 2002 suite \u00e0 l\u2019appel d\u2019offre INSERM sur les Centres de Ressources Biologiques. Le CRB traite les \u00e9chantillons provenant de patients atteints de Cancers du poumon et m\u00e9soth\u00e9liomes pleuraux, ainsi que du sang, plasma et s\u00e9rum. Il collabore avec plusieurs instituts tels que l\u2019INCa, la Ligue contre le Cancer, plusieurs CHU (Nice, Grenoble, Lyon et Caen). Le C.R.B. est sp\u00e9cialis\u00e9 dans l\u2019acquisition, la validation et la distribution d\u2019\u00e9chantillons biologiques annot\u00e9s provenant de malades atteints de \u00ab cancers bronchiques et de m\u00e9soth\u00e9liomes pleuraux \u00bb. ",
    "presentation_en": "The Centre de Ressources Biologiques (CRB) of the CHU of Nancy devotes itself to research in cancerology and more particularly to lung cancer.The CRB was selected for the project of the Ligue Nationale contre le cancer\/Institut National du Cancer: \u201cIndentity card of the pulmonary Tumours or CIT\u201d. For this reason the \u201cindentity card\u201d of genes of 80 tumours is initially established to specify \u201cthe distinguishing marks\u201d of the 40 most aggressive tumours. The CRB human samples were dissected under a microscope to separate tumoral tissue from healthy tissue, then their genome (DNA) was extracted and analyzed on the chip \u201cindentity card the tumours\u201d of the Ligue Nationale Contre le Cancer. Samples were analyzed again to confirm the first. This work coordinated by the CRB of Nancy, is completed in collaboration with the Institute of Genetics and Molecular biology of Strasbourg (Dr. Stanislas Du Manoir), the CHU of Caen (pr. Francoise Galateau Salle) and CNRS in Poitiers (Dr. Joelle Roche).The CRB is strongly impliqued in the Programme National d\u2019Excellence Scientifique (PNES) \u201cmolecular Epidemiology of lung cancers professional\u201d where it is a question of identifying association between the occupational hazards and the clinical results, histological, anatomical, and prognostic and between molecular deteriorations and the exposures to the professionals carcinogenics.The CRB is implied in the research of the \u201cmutations of the EGFR gene in lung cancer: description of a molecular target allowing a specific access to the targeted therapies\u201d initiated by the Institut National du Cancer. So the CRB developed the protocols to detect the mutations in exons 19 (by analysis of fragments), 20 (by PCR of sequencing) and 21 (by enzymatic digestion). For each sample the tumoral zone is dissected and an evaluation of the percentage of tumoral cells is carried out.",
    "vitrine": "",
    "sampling_practice": "",
    "materialStoredPlasma": "",
    "materialStoredRNA": null,
    "materialStoredSaliva": null,
    "materialStoredSerum": "",
    "materialStoredTissueFFPE": "",
    "materialStoredTissueFrozen": "",
    "materialStoredUrine": null,
    "materialStoredBlood": null,
    "materialStoredDNA": "",
    "materialStoredFaeces": null,
    "materialStoredImmortalizedCellLines": null,
    "materialTumoralTissue": null,
    "materialHealthyTissue": null,
    "materialLCR": null,
    "materialOther": null,
    "sampling_disease_group": "",
    "sampling_disease_group_code": "",
    "nb_total_samples": null,
    "collectionDataAccessFee": "TRUE",
    "collectionDataAccessJointProjects": "TRUE",
    "collectionSampleAccessFee": "TRUE",
    "collectionSampleAccessJointProjects": "TRUE",
    "PartnerCharterSigned": "",
    "nbs_dna_samples_affected": "",
    "nbs_dna_samples_relatives": "",
    "nbs_cdna_samples_affected": "",
    "nbs_cdna_samples_relatives": "",
    "nbs_wholeblood_samples_affected": "",
    "nbs_wholeblood_samples_relatives": "",
    "nbs_bloodcellisolates_samples_affected": "",
    "nbs_bloodcellisolates_samples_relatives": "",
    "nbs_serum_samples_affected": "",
    "nbs_serum_samples_relatives": "",
    "nbs_plasma_samples_affected": "",
    "nbs_plasma_samples_relatives": "",
    "nbs_fluids_samples_affected": "",
    "nbs_fluids_samples_relatives": "",
    "nbs_tissuescryopreserved_samples_affected": "",
    "nbs_tissuescryopreserved_samples_relatives": "",
    "nbs_tissuesparaffinembedded_samples_affected": "",
    "nbs_tissuesparaffinembedded_samples_relatives": "",
    "nbs_celllines_samples_affected": "",
    "nbs_celllines_samples_relatives": "",
    "nbs_other_samples_affected": "",
    "nbs_other_samples_relatives": "",
    "nbs_other_specification": "",
    "cims": [],
    "contact_search": "",
    "cert_ISO9001": "OUI",
    "cert_NFS96900": "OUI",
    "cert_autres": "\/"
});
db.biobank.insert({
    "id": "9",
    "identifier": "BB-0033-99995",
    "name": "biobank n\u00b0 5",
    "long_name": "Biobanque 5 - CRB5 - Paris",
    "collection_name": "Oncologie - Canc\u00e9rologie - Cancer: cancers pleuropulmonaires, bronchopulmonaires, m\u00e9soth\u00e9liomes, lymphomes (LLC), cancers des voies a\u00e9ro-digestives, du tube digestif \/ Cancers secondaires \u00e0 une exposition professionnelle - maladies professionnelles",
    "collection_id": "Mesoth\u00e9liomes",
    "biobank_class": "biobankClinical",
    "date_entry": "05\/01\/2015",
    "folder_reception": "\/inserm_sftp\/caen_tumo\/reception",
    "folder_done": "\/inserm_sftp\/caen_tumo\/inclusion",
    "passphrase": "caenbb14",
    "contact_id": "550c3a40843cbc6525226978",
    "diagnosis_available": "C00-D48 \/ Other",
    "pathologies": null,
    "pathologies_en": null,
    "longitude": "-0,3535338",
    "latitude": "49,2020005",
    "location": null,
    "keywords_MeSH": "",
    "keywords_MeSH_fr": null,
    "acronym": null,
    "presentation": "La tumoroth\u00e8que de Caen Basse-Normandie (TCBN) est un Groupement de Coop\u00e9ration Sanitaire entre le Centre de Lutte Contre le Cancer, Fran\u00e7ois Baclesse et le CHU de Caen. Les echantillons conserv\u00e9s (tissus tumoraux et sains, cellules, s\u00e9rums, liquides\u2026) le sont dans le cadre du soin et permettent de constituer des collections en canc\u00e9rologie pour une finalit\u00e9 de recherche. Le CRB m\u00e9soth\u00e9liome MESOBANK est une biobanque nationale sp\u00e9cialis\u00e9e sur le m\u00e9soth\u00e9liome en lien avec la TCBN",
    "presentation_en": "The TCBN is part of the National Virtual Lung Tumor Bank (TVN lung) which represents a network of seven French biobanks active in collecting lung cancer tissues, with a central catalogue of collected specimens and  standardized annotations. The TCBN has adopted the minimal common protocols for collection, quality control and processing of specimens in collaboration with the CIRC in Lyon (Pierre Hainaut). We aim to be part of multicentric national projects in pharmacogenomic, first to use mutations as markers to rebuilt the history of lung cancers and to evaluate or distinguish biomarkers associated with high metastatic\/evolutive potential or for targeted therapies (ex: post- transcriptional TUBB3 expression via Ras  through miR200c is associated with a non response to chemotherapy) , second to identify biomarkers specific of asbestos-induced carcinogenesis (inactivation of p16INK4a\/p14arf on chromosome 9p21 and neurofibromatosis type 2(NF2). Our catalogue contains more than 1300 indexed available tumors.\r\n\r\nThe MESOBANK is a National  specialized biobank on mesothelioma linked to the MESOPATH national referral center  and to the International mesothelioma excellence center IM@EC and to a basic research team UMR 674. Pathologists play a crucial role in validating diagnosis by immunohistochemistry on the tissue, novel prognostic and predictive markers capable of improving the overall patient management, and by their participation in the Mesothelioma Virtual Bank. This ressource contains clinical data, follow up and access to human mesotheliomas, normal specimens and mesothelioma cell lines. It provides a high quality potential for translational research studies. Recent molecular analyses of mesothelioma tissues and cells, were developed to identify specific circulating markers (mesothelin), to better characterize mesothelioma subclasses, to determine chromosomal imbalances (CGH arrays), alterations of signaling pathways, and to define the immunological context. These investigations will provide new tools for early and reliable diagnosis of mesothelioma and improvement of patients management based on clinical development and validation of innovative drugs and strategies.\r\n",
    "vitrine": null,
    "sampling_practice": "",
    "materialStoredPlasma": null,
    "materialStoredRNA": null,
    "materialStoredSaliva": null,
    "materialStoredSerum": null,
    "materialStoredTissueFFPE": null,
    "materialStoredTissueFrozen": null,
    "materialStoredUrine": null,
    "materialStoredBlood": null,
    "materialStoredDNA": null,
    "materialStoredFaeces": null,
    "materialStoredImmortalizedCellLines": null,
    "materialTumoralTissue": null,
    "materialHealthyTissue": null,
    "materialLCR": null,
    "materialOther": null,
    "sampling_disease_group": "",
    "sampling_disease_group_code": "",
    "nb_total_samples": null,
    "collectionDataAccessFee": "TRUE",
    "collectionDataAccessJointProjects": "TRUE",
    "collectionSampleAccessFee": "TRUE",
    "collectionSampleAccessJointProjects": "TRUE",
    "PartnerCharterSigned": "TRUE",
    "nbs_dna_samples_affected": "",
    "nbs_dna_samples_relatives": "",
    "nbs_cdna_samples_affected": "",
    "nbs_cdna_samples_relatives": "",
    "nbs_wholeblood_samples_affected": "",
    "nbs_wholeblood_samples_relatives": "",
    "nbs_bloodcellisolates_samples_affected": "",
    "nbs_bloodcellisolates_samples_relatives": "",
    "nbs_serum_samples_affected": "",
    "nbs_serum_samples_relatives": "",
    "nbs_plasma_samples_affected": "",
    "nbs_plasma_samples_relatives": "",
    "nbs_fluids_samples_affected": "",
    "nbs_fluids_samples_relatives": "",
    "nbs_tissuescryopreserved_samples_affected": "",
    "nbs_tissuescryopreserved_samples_relatives": "",
    "nbs_tissuesparaffinembedded_samples_affected": "",
    "nbs_tissuesparaffinembedded_samples_relatives": "",
    "nbs_celllines_samples_affected": "",
    "nbs_celllines_samples_relatives": "",
    "nbs_other_samples_affected": "",
    "nbs_other_samples_relatives": "",
    "nbs_other_specification": "",
    "cims": [],
    "contact_search": null,
    "cert_ISO9001": "EN COURS",
    "cert_NFS96900": "EN COURS",
    "cert_autres": "\/"
});
db.biobank.insert({
    "id": "21",
    "identifier": "BB-0033-99996",
    "name": "biobank n\u00b0 6",
    "long_name": "Biobanque 6 - CRB6 - Paris",
    "collection_name": "Infectiologie \/ Immunologie \/ Neurologie",
    "collection_id": "Infectiologie \/ Immunologie \/ Neurologie",
    "biobank_class": "",
    "date_entry": "",
    "folder_reception": "",
    "folder_done": "",
    "passphrase": "",
    "contact_id": "552fe5e30175447b308b456c",
    "diagnosis_available": "A00-B00 \/ D50-D89 \/ E00-E90 \/ K00-K93 \/ L00-L99 \/ G00-G99",
    "pathologies": null,
    "pathologies_en": null,
    "longitude": "2,3522219",
    "latitude": "48,856614",
    "location": {
        "type": "Point",
        "coordinates": [
            2.3522219,
            48.856614
        ]
    },
    "keywords_MeSH": "Infectious diseases \u2013 Emerging agents - Immunology \u2013\u2013 Vaccination \u2013 Inflammation \u2013 Genetics \u2013 Translational research \u2013 Cohort \u2013 Healthy volunteers.",
    "keywords_MeSH_fr": null,
    "acronym": "",
    "presentation": "La plateforme ICAReB (Investigation Clinique et Acc\u00e8s aux Ressources Biologiques) de l\u2019Institut Pasteur a une double activit\u00e9 : investigation clinique et centre de ressources biologiques non seulement \u00e0 l\u2019usage des chercheurs du campus pasteurien, mais \u00e9galement de la communaut\u00e9 scientifique internationale. C\u2019est l\u2019environnement pasteurien sp\u00e9cialis\u00e9 tout particuli\u00e8rement en infectiologie, immunologie et g\u00e9n\u00e9tique li\u00e9e \u00e0 ces domaines, qui a fa\u00e7onn\u00e9 les activit\u00e9s de la biobanque depuis sa cr\u00e9ation en 2005. Les \u00e9chantillons humains (s\u00e9rums, plasmas, cellules monoclu\u00e9es du sang (PBMCs), urines, \u00e9couvillons, larmes, selles, salives, ADN\/ARN\u2026) sont conserv\u00e9s \u00e0 diff\u00e9rentes temp\u00e9ratures ( -196\u00b0C, -80\u00b0C, +4\u00b0C et temp\u00e9rature ambiante) proviennent de cohortes de volontaires sains (collections propres) et de patients (collections collaboratives).",
    "presentation_en": "ICAReB (Clinical Investigation and Access to Biological Resources) has been redefined as a platform within the Institut Pasteur\u2019s campus at the beginning of 2008. As such, it endorses 2 main transversal activities open to the scientific community working on infectious diseases and immunity :\u2022\ta clinical investigation activity, which ensures accurate recruitment and follow-up of well-characterized volunteers \u2013 healthy or patients -, participating to research protocols,\u2022\ta biobank activity, which allows all human samples to be collected, then prepared, preserved, and distributed following the best standards of quality. The quality process led to ISO 9001v:2000 certification of the biobank activity in 2007 and NF-S96-900 in 2009.Recently, new protocols started in 3 main fields : \uf0e0 diagnosis of infectious diseases : -\tICAReB manages WHO\u2019s biobank of Human African Trypanosomiasis, to promote new performing, cost-effective and simple diagnostic methods of this disease ;-\tThe \u201cDIAGMICOLL\u201d cohort, allows through a wide range of samples, the setting up and validation of new diagnostic methods in the field of infectious and tropical diseases.\uf0e0 knowledge of different pathologies with infectious expression : -\tThe Hidrosadenitis suppurativa (Verneuil\u2019s disease) project, adresses the genetic bases of this disease, -\tThe Pathodisc protocol has been conceived to screen the samples of patients who present with infectious syndrome without by new high-throughput methods, so as to find out the causative agent.-\tMucolfa project proposes to search for the agent(s) causing anosmia in a proportion of patients, after iterative viral attacks.\uf0e0 validation of the methods of preparation and preservation of the bio-resources.\tThis has started with a project with BRCs from the French Network, to optimise the pre-analytical quality of different sort of samples on proteomic criteria (serum, buffy coats\u2026). The platform is currently undertaking a new validation on the cryo-preservation of peripheral blood mononuclear cells, so as to ascertain a good viability and functionality after thawing, on phenotyping and functional criteria.",
    "vitrine": null,
    "sampling_practice": "",
    "materialStoredPlasma": "",
    "materialStoredRNA": null,
    "materialStoredSaliva": null,
    "materialStoredSerum": "",
    "materialStoredTissueFFPE": "",
    "materialStoredTissueFrozen": "",
    "materialStoredUrine": null,
    "materialStoredBlood": null,
    "materialStoredDNA": "",
    "materialStoredFaeces": null,
    "materialStoredImmortalizedCellLines": null,
    "materialTumoralTissue": null,
    "materialHealthyTissue": null,
    "materialLCR": null,
    "materialOther": null,
    "sampling_disease_group": "",
    "sampling_disease_group_code": "",
    "nb_total_samples": null,
    "collectionDataAccessFee": "TRUE",
    "collectionDataAccessJointProjects": "TRUE",
    "collectionSampleAccessFee": "TRUE",
    "collectionSampleAccessJointProjects": "TRUE",
    "PartnerCharterSigned": "",
    "nbs_dna_samples_affected": "",
    "nbs_dna_samples_relatives": "",
    "nbs_cdna_samples_affected": "",
    "nbs_cdna_samples_relatives": "",
    "nbs_wholeblood_samples_affected": "",
    "nbs_wholeblood_samples_relatives": "",
    "nbs_bloodcellisolates_samples_affected": "",
    "nbs_bloodcellisolates_samples_relatives": "",
    "nbs_serum_samples_affected": "",
    "nbs_serum_samples_relatives": "",
    "nbs_plasma_samples_affected": "",
    "nbs_plasma_samples_relatives": "",
    "nbs_fluids_samples_affected": "",
    "nbs_fluids_samples_relatives": "",
    "nbs_tissuescryopreserved_samples_affected": "",
    "nbs_tissuescryopreserved_samples_relatives": "",
    "nbs_tissuesparaffinembedded_samples_affected": "",
    "nbs_tissuesparaffinembedded_samples_relatives": "",
    "nbs_celllines_samples_affected": "",
    "nbs_celllines_samples_relatives": "",
    "nbs_other_samples_affected": "",
    "nbs_other_samples_relatives": "",
    "nbs_other_specification": "",
    "cims": [],
    "contact_search": "",
    "cert_ISO9001": "OUI",
    "cert_NFS96900": "OUI",
    "cert_autres": "ISO 17025"
});
db.biobank.insert({
    "id": "22",
    "identifier": "BB-0033-99997",
    "name": "biobank n\u00b0 7",
    "long_name": "Biobanque 7 - CRB7 - Paris",
    "collection_name": "Pathologies cardiovasculaires \/ Pathologies m\u00e9taboliques \/ Pathologies neurod\u00e9g\u00e9n\u00e9ratives \/ Etudes multicentriques exclusivement",
    "collection_id": "Pathologies cardiovasculaires \/ Pathologies m\u00e9taboliques \/ Pathologies neurod\u00e9g\u00e9n\u00e9ratives \/ Etudes multicentriques exclusivement",
    "biobank_class": "",
    "date_entry": "",
    "folder_reception": "",
    "folder_done": "",
    "passphrase": "",
    "contact_id": "552fe5e30175447b308b4571",
    "diagnosis_available": "I00-I99 \/ E00-E90 \/ G00-G99 \/ F00-F99",
    "pathologies": null,
    "pathologies_en": null,
    "longitude": "3,057256",
    "latitude": "50,62925",
    "location": {
        "type": "Point",
        "coordinates": [
            3.057256,
            50.62925
        ]
    },
    "keywords_MeSH": "\/",
    "keywords_MeSH_fr": null,
    "acronym": "",
    "presentation": "Depuis une dizaine d'ann\u00e9es, le laboratoire d\u2019analyse g\u00e9nomique (LAG) d\u00e9veloppe les activit\u00e9s suivantes : la collecte, le traitement, le stockage, la gestion et la distribution d'\u00e9chantillons d'origine humaine. Le LAG est actuellement gestionnaire des \u00e9chantillons sanguins de plus de 22500 sujets provenant principalement d'\u00e9tudes \u00e9pid\u00e9miologiques bas\u00e9es sur les th\u00e9matiques maladies cardiovasculaires, m\u00e9taboliques et neurod\u00e9g\u00e9n\u00e9ratives.",
    "presentation_en": "The studies included in the LAG-CRB have common objectives, which are to highlight gene-environment interactions in the occurrence of human diseases mainly orientated towards cardiovascular and metabolic diseases and neurodegenerative disorders. They all require a large number of patients in order to have a sufficient power to detect associations between genetic variations and phenotypes. All these studies require biological sampling allowing DNA extraction for high throughput genotyping and sequencing.As a prerequisite, the biological samples stored and informations need to be reliable. Thus quality requirements are our constant concern since the creation of the LAG-CRB.The growing number of samples to manage (more than 215 000 samples July 1st, 2010) reinforces the setting up of a quality management system (on the basis of the standart NF S 96-900) to maintain the satisfaction of our partners and the recognition of our services by the researchers and the institutions. ",
    "vitrine": null,
    "sampling_practice": "",
    "materialStoredPlasma": "",
    "materialStoredRNA": null,
    "materialStoredSaliva": null,
    "materialStoredSerum": "",
    "materialStoredTissueFFPE": "",
    "materialStoredTissueFrozen": "",
    "materialStoredUrine": null,
    "materialStoredBlood": null,
    "materialStoredDNA": "",
    "materialStoredFaeces": null,
    "materialStoredImmortalizedCellLines": null,
    "materialTumoralTissue": null,
    "materialHealthyTissue": null,
    "materialLCR": null,
    "materialOther": null,
    "sampling_disease_group": "",
    "sampling_disease_group_code": "",
    "nb_total_samples": null,
    "collectionDataAccessFee": "TRUE",
    "collectionDataAccessJointProjects": "TRUE",
    "collectionSampleAccessFee": "TRUE",
    "collectionSampleAccessJointProjects": "TRUE",
    "PartnerCharterSigned": "",
    "nbs_dna_samples_affected": "",
    "nbs_dna_samples_relatives": "",
    "nbs_cdna_samples_affected": "",
    "nbs_cdna_samples_relatives": "",
    "nbs_wholeblood_samples_affected": "",
    "nbs_wholeblood_samples_relatives": "",
    "nbs_bloodcellisolates_samples_affected": "",
    "nbs_bloodcellisolates_samples_relatives": "",
    "nbs_serum_samples_affected": "",
    "nbs_serum_samples_relatives": "",
    "nbs_plasma_samples_affected": "",
    "nbs_plasma_samples_relatives": "",
    "nbs_fluids_samples_affected": "",
    "nbs_fluids_samples_relatives": "",
    "nbs_tissuescryopreserved_samples_affected": "",
    "nbs_tissuescryopreserved_samples_relatives": "",
    "nbs_tissuesparaffinembedded_samples_affected": "",
    "nbs_tissuesparaffinembedded_samples_relatives": "",
    "nbs_celllines_samples_affected": "",
    "nbs_celllines_samples_relatives": "",
    "nbs_other_samples_affected": "",
    "nbs_other_samples_relatives": "",
    "nbs_other_specification": "",
    "cims": [],
    "contact_search": "",
    "cert_ISO9001": "NON",
    "cert_NFS96900": "EN COURS",
    "cert_autres": "\/"
});
db.biobank.insert({
    "id": "23",
    "identifier": "BB-0033-99998",
    "name": "biobank n\u00b0 8",
    "long_name": "Biobanque 8 - CRB8 - Paris",
    "collection_name": "Oncologie - Canc\u00e9rologie - Cancer: tumeurs digestives, ORL, respiratoires, gyn\u00e9cologiques, tumerus ORL rares, surr\u00e9naliennes \/ Pathologies cardiovasculaires \/ Dysplasie fibromusculaire",
    "collection_id": "Oncologie - Canc\u00e9rologie - Cancer: tumeurs digestives, ORL, respiratoires, gyn\u00e9cologiques, tumerus ORL rares, surr\u00e9naliennes \/ Pathologies cardiovasculaires \/ Dysplasie fibromusculaire",
    "biobank_class": "",
    "date_entry": "",
    "folder_reception": "",
    "folder_done": "",
    "passphrase": "",
    "contact_id": "552fe5e40175447b308b4576",
    "diagnosis_available": "C00-D48 \/ I00-I99 \/ M00-M99",
    "pathologies": null,
    "pathologies_en": null,
    "longitude": "2,2761151",
    "latitude": "48,8390821",
    "location": {
        "type": "Point",
        "coordinates": [
            2.2761151,
            48.8390821
        ]
    },
    "keywords_MeSH": "Certification, blood collections, tissue banks, cryopreservation",
    "keywords_MeSH_fr": null,
    "acronym": "",
    "presentation": "N\u00e9e r\u00e9cemment de la f\u00e9d\u00e9ration des activit\u00e9s du CRB et de la Tumoroth\u00e8que de l\u2019HEGP, la nouvelle Plate-Forme de Ressources Biologiques (PRB-HEGP) articule son activit\u00e9 autour des deux principaux p\u00f4les d\u2019activit\u00e9 de l\u2019HEGP : l\u2019oncologie et le cardiovasculaire. Au sein de la PRB-HEGP, le CRB est responsable de la gestion des \u00e9chantillons non tissulaires \u00e0 vis\u00e9e de recherche et la Tumoroth\u00e8que de la gestion des \u00e9chantillons tissulaires sains ou pathologiques collectionn\u00e9s \u00e0 vis\u00e9e de recherche ou recueillis dans un cadre de soin, mais pouvant \u00eatre re-qualifi\u00e9s pour la recherche.",
    "presentation_en": "Organized in the center of Biology and Health Products, the Platform for Biological Resources (PRB-HEGP) is a new facility stemming from grouping BRC activities, involved in managing collections of biological samples for research dedicated to the medico-scientific community of HEGP, with the tumor bank, responsible for the freezing of tissue samples collected specifically for research purposes, or collected in a framework of care that may be re-qualified for research. The platform offers a new organization in the management of biological resources that meets both the clinical requirements and the needs of research programs initiated by the medical community of HEGP. Since its creation the PRB-HEGP is engaged in a quality assurance process in order to qualify for certification to standard PRB NF S96-900 for the first half of 2012. First step in this process was a new definition of the responsibilities of the different actors on the samples (clinicians, surgeons, pathologists, operating room personnel, nurses, PRB staff) and new procedures to optimize circuits, reduce the time from collection to freezing of samples and ensure their traceability. The treatment and storage operations and provision of samples are made according to defined and validated procedures and operating modes. The technical staff who ensure the preparation and freezing of samples is trained in quality practices. A sample management software (Biobase 2) allows to trace all operations performed on the samples and to record the associated annotations. The software enables a unique and anonymized identification of each sample by cryogenic labels barcode. Securing storage conditions are provided by the Thermo-control system which ensures the traceability of temperatures and generates alarms in case of malfunction. PRB-HEGP manages since 2008 of more than forty clinical trials for industry and a dozen institutional projects.- The activity of the tumor bank for health and research has led to the freezing of over 1900 tissue samples in 2009.",
    "vitrine": null,
    "sampling_practice": "",
    "materialStoredPlasma": "",
    "materialStoredRNA": null,
    "materialStoredSaliva": null,
    "materialStoredSerum": "",
    "materialStoredTissueFFPE": "",
    "materialStoredTissueFrozen": "",
    "materialStoredUrine": null,
    "materialStoredBlood": null,
    "materialStoredDNA": "",
    "materialStoredFaeces": null,
    "materialStoredImmortalizedCellLines": null,
    "materialTumoralTissue": null,
    "materialHealthyTissue": null,
    "materialLCR": null,
    "materialOther": null,
    "sampling_disease_group": "",
    "sampling_disease_group_code": "",
    "nb_total_samples": null,
    "collectionDataAccessFee": "TRUE",
    "collectionDataAccessJointProjects": "TRUE",
    "collectionSampleAccessFee": "TRUE",
    "collectionSampleAccessJointProjects": "TRUE",
    "PartnerCharterSigned": "",
    "nbs_dna_samples_affected": "",
    "nbs_dna_samples_relatives": "",
    "nbs_cdna_samples_affected": "",
    "nbs_cdna_samples_relatives": "",
    "nbs_wholeblood_samples_affected": "",
    "nbs_wholeblood_samples_relatives": "",
    "nbs_bloodcellisolates_samples_affected": "",
    "nbs_bloodcellisolates_samples_relatives": "",
    "nbs_serum_samples_affected": "",
    "nbs_serum_samples_relatives": "",
    "nbs_plasma_samples_affected": "",
    "nbs_plasma_samples_relatives": "",
    "nbs_fluids_samples_affected": "",
    "nbs_fluids_samples_relatives": "",
    "nbs_tissuescryopreserved_samples_affected": "",
    "nbs_tissuescryopreserved_samples_relatives": "",
    "nbs_tissuesparaffinembedded_samples_affected": "",
    "nbs_tissuesparaffinembedded_samples_relatives": "",
    "nbs_celllines_samples_affected": "",
    "nbs_celllines_samples_relatives": "",
    "nbs_other_samples_affected": "",
    "nbs_other_samples_relatives": "",
    "nbs_other_specification": "",
    "cims": [],
    "contact_search": "",
    "cert_ISO9001": "EN COURS",
    "cert_NFS96900": "OUI",
    "cert_autres": "\/"
});
db.biobank.insert({
    "id": "24",
    "identifier": "BB-0033-99999",
    "name": "biobank n\u00b0 9",
    "long_name": "Biobanque 9 - CRB9 - Paris",
    "collection_name": "Oncologie - Canc\u00e9rologie - Cancer: h\u00e9mopathies malignes, tumeurs urologiques, tumeurs solides p\u00e9diatriques, cancer du sein \/ mammaire... \/ Maladies et malformations cong\u00e9nitales associ\u00e9es \/ Maladies g\u00e9n\u00e9tiques rares",
    "collection_id": "Oncologie - Canc\u00e9rologie - Cancer: h\u00e9mopathies malignes, tumeurs urologiques, tumeurs solides p\u00e9diatriques, cancer du sein \/ mammaire... \/ Maladies et malformations cong\u00e9nitales associ\u00e9es \/ Maladies g\u00e9n\u00e9tiques rares",
    "biobank_class": "",
    "date_entry": "",
    "folder_reception": "",
    "folder_done": "",
    "passphrase": "",
    "contact_id": "552fe5e40175447b308b457b",
    "diagnosis_available": "A00-B99 \/ C00-D48 \/ D50-D89 \/ E00-E90 \/ G00-G99 \/ H00-H59 \/ I00-I99 \/ J00-J99 \/ K00-K93 \/ L00-L99 \/ N00-N99 \/ Q00-Q99",
    "pathologies": null,
    "pathologies_en": null,
    "longitude": "2,3154486",
    "latitude": "48,8463504",
    "location": {
        "type": "Point",
        "coordinates": [
            2.3154486,
            48.8463504
        ]
    },
    "keywords_MeSH": "\/",
    "keywords_MeSH_fr": null,
    "acronym": "",
    "presentation": "La Plateforme de Ressources Biologiques de l\u2019h\u00f4pital Necker-Enfants Malades (PRB NECKER) est constitu\u00e9e du CRB-ADN-NECKER (banque d'ADN et de cellules lymphoblastiques) et de la PRB du P\u00f4le de Biologie et Produits de Sant\u00e9. Cette derni\u00e8re comprend:1. La tumoroth\u00e8que avec l\u2019anatomie pathologique :Axe Tissuth\u00e8que \/ Tumeurs Solides (tissus, ADNs, ARNs) et l\u2019onco-h\u00e9matologie : Axe H\u00e9mopathies Malignes (cellules, ADNs, ARNs)2. L\u2019Ensemble des Services du P\u00f4le de Biologie, \u00e0 savoir l\u2019Histo-Embryo-Cytog\u00e9n\u00e9tique, la Bact\u00e9rio-Virologie, la Biochimie g\u00e9n\u00e9rale, la biochimie m\u00e9tabolomique, l\u2019Immunologie, les explorations fonctionnelles\u2026 (s\u00e9rum, plasma, tissus, cellules et lign\u00e9es cellulaires, Acides Nucl\u00e9iques, urines, liquides amniotiques...)",
    "presentation_en": "Description of the specific features of the collected samples:For Necker tissue and cellulotek :- Collection of samples to establish and precise the diagnosis, mostly in difficult and rare pathologies- Important medical programs at Necker-Enfants Malades hospital : Adult and pediatric Onco-haematology, adult and pediatric solid tumours, adult and pediatric transplantation- Medical specialities: pediatric neuro-surgery, visceral surgery, adult and pediatric cardiology, haematology, dermatology, gastroenterology, adult and pediatric nephrology, kidney and digestive transplantation, pneumo-allergology, urology- Freezing and conservation with obligatory health aim- Then, possibility to make available samples in order to promote scientific research- Ongoing, 26 scientific plans and 5 national protocolsPlanned development : - increase of scientific plans - getting of ISO 9001-2000 certification which will allow to control all collecting stages : samples transport, freezing in laboratories, long conservation, transformation in DNA or RNA and cession- active participation in national or European networks- getting of new funds in order to recruit new employees- participation at the increase of the hospital competitivenessFor CRB-ADNTwo types of samples are stored in the Necker DNA biobank: (i) either samples from patients (almost only children) with rare genetic disorders who are attending the various specialized departments of the Children hospital. The children are often in a life-threatening situation. The disease is generally not yet characterized and DNA should be stored either for later inclusion in a research project aiming at identifying the gene involved in the corresponding disease, especially if several samples from the same pathology group could have been collected or for diagnostic purposes when the underlying gene (or gene locus) is identified. This is particularly crucial when the proband is deceased and the stored sample is the only way to provide accurate genetic counseling to the family; (ii) or samples which are part of collections generated through a defined research project. In all cases, an informed consent from the patient or his\/her parents has been obtained and the signed form is conserved in the DNA biobank. The first group of samples is currently the most abundant, and represents more than 30000 samples (either leukocyte pellets, PBL or but less frequently, lymphoblastoid cell lines) from ~20 000 patients (and their affected or unaffected relatives). The second group is currently increasing since the reopening and reorganization of the DNA biobank. Several projects have been implemented. ",
    "vitrine": null,
    "sampling_practice": "1",
    "materialStoredPlasma": "",
    "materialStoredRNA": null,
    "materialStoredSaliva": null,
    "materialStoredSerum": "",
    "materialStoredTissueFFPE": "",
    "materialStoredTissueFrozen": "",
    "materialStoredUrine": null,
    "materialStoredBlood": null,
    "materialStoredDNA": "",
    "materialStoredFaeces": null,
    "materialStoredImmortalizedCellLines": null,
    "materialTumoralTissue": null,
    "materialHealthyTissue": null,
    "materialLCR": null,
    "materialOther": null,
    "sampling_disease_group": "",
    "sampling_disease_group_code": "diagnosis",
    "nb_total_samples": null,
    "collectionDataAccessFee": "TRUE",
    "collectionDataAccessJointProjects": "TRUE",
    "collectionSampleAccessFee": "TRUE",
    "collectionSampleAccessJointProjects": "TRUE",
    "PartnerCharterSigned": "",
    "nbs_dna_samples_affected": "",
    "nbs_dna_samples_relatives": "",
    "nbs_cdna_samples_affected": "",
    "nbs_cdna_samples_relatives": "",
    "nbs_wholeblood_samples_affected": "",
    "nbs_wholeblood_samples_relatives": "",
    "nbs_bloodcellisolates_samples_affected": "",
    "nbs_bloodcellisolates_samples_relatives": "",
    "nbs_serum_samples_affected": "",
    "nbs_serum_samples_relatives": "",
    "nbs_plasma_samples_affected": "",
    "nbs_plasma_samples_relatives": "",
    "nbs_fluids_samples_affected": "",
    "nbs_fluids_samples_relatives": "",
    "nbs_tissuescryopreserved_samples_affected": "",
    "nbs_tissuescryopreserved_samples_relatives": "",
    "nbs_tissuesparaffinembedded_samples_affected": "",
    "nbs_tissuesparaffinembedded_samples_relatives": "",
    "nbs_celllines_samples_affected": "",
    "nbs_celllines_samples_relatives": "",
    "nbs_other_samples_affected": "",
    "nbs_other_samples_relatives": "",
    "nbs_other_specification": "",
    "cims": [],
    "contact_search": "",
    "cert_ISO9001": "NON",
    "cert_NFS96900": "OUI",
    "cert_autres": "\/"
});
db.user.insert({
    "id": "1",
    "prenom": "prenom0",
    "nom": "nom0",
    "login": "login0",
    "password": "pwd@0",
    "email": "user0@testmail.fr",
    "telephone": null,
    "gsm": "0600010000",
    "profil": "0",
    "inactif": "0",
    "biobank_id": null,
    "inscription_date": {
        "sec": 1474633494,
        "usec": 772000
    }
});
db.user.insert({
    "id": "2",
    "prenom": "prenom1",
    "nom": "nom1",
    "login": "login1",
    "password": "pwd@1",
    "email": "user1@testmail.fr",
    "telephone": null,
    "gsm": "0600010001",
    "profil": "1",
    "inactif": "1",
    "biobank_id": null,
    "inscription_date": {
        "sec": 1474633494,
        "usec": 772000
    }
});
db.user.insert({
    "id": "3",
    "prenom": "prenom2",
    "nom": "nom2",
    "login": "login2",
    "password": "pwd@2",
    "email": "user2@testmail.fr",
    "telephone": null,
    "gsm": "0600010002",
    "profil": "2",
    "inactif": "0",
    "biobank_id": null,
    "inscription_date": {
        "sec": 1474633494,
        "usec": 772000
    }
});
db.user.insert({
    "id": null,
    "prenom": "prenom3",
    "nom": "nom3",
    "login": "login3",
    "password": "pwd@3",
    "email": "user3@testmail.fr",
    "telephone": null,
    "gsm": "0600010003",
    "profil": "0",
    "inactif": "1",
    "biobank_id": null,
    "inscription_date": {
        "sec": 1474633494,
        "usec": 772000
    }
});
db.user.insert({
    "id": "6",
    "prenom": "prenom4",
    "nom": "nom4",
    "login": "login4",
    "password": "pwd@4",
    "email": "user4@testmail.fr",
    "telephone": null,
    "gsm": "0600010004",
    "profil": "1",
    "inactif": "0",
    "biobank_id": null,
    "inscription_date": {
        "sec": 1474633494,
        "usec": 772000
    }
});
db.user.insert({
    "id": null,
    "prenom": "prenom5",
    "nom": "nom5",
    "login": "login5",
    "password": "pwd@5",
    "email": "user5@testmail.fr",
    "telephone": null,
    "gsm": "0600010005",
    "profil": "2",
    "inactif": "1",
    "biobank_id": null,
    "inscription_date": {
        "sec": 1474633494,
        "usec": 772000
    }
});
db.user.insert({
    "id": null,
    "prenom": "prenom6",
    "nom": "nom6",
    "login": "login6",
    "password": "pwd@6",
    "email": "user6@testmail.fr",
    "telephone": null,
    "gsm": "0600010006",
    "profil": "0",
    "inactif": "0",
    "biobank_id": null,
    "inscription_date": {
        "sec": 1474633494,
        "usec": 772000
    }
});
db.user.insert({
    "id": null,
    "prenom": "prenom7",
    "nom": "nom7",
    "login": "login7",
    "password": "pwd@7",
    "email": "user7@testmail.fr",
    "telephone": null,
    "gsm": "0600010007",
    "profil": "1",
    "inactif": "1",
    "biobank_id": null,
    "inscription_date": {
        "sec": 1474633494,
        "usec": 772000
    }
});
db.user.insert({
    "id": null,
    "prenom": "prenom8",
    "nom": "nom8",
    "login": "login8",
    "password": "pwd@8",
    "email": "user8@testmail.fr",
    "telephone": null,
    "gsm": "0600010008",
    "profil": "2",
    "inactif": "0",
    "biobank_id": null,
    "inscription_date": {
        "sec": 1474633494,
        "usec": 772000
    }
});
db.user.insert({
    "id": null,
    "prenom": "prenom9",
    "nom": "nom9",
    "login": "login9",
    "password": "pwd@9",
    "email": "user9@testmail.fr",
    "telephone": null,
    "gsm": "0600010009",
    "profil": "0",
    "inactif": "1",
    "biobank_id": null,
    "inscription_date": {
        "sec": 1474633494,
        "usec": 772000
    }
});
